apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: argo
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - workflowtaskresults
    - workflowstasksets
    - workflowtemplates
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete